// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250816021228_removendo_indice_unico_number")]
    partial class removendo_indice_unico_number
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Susie Bins"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nora Ebert"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shelly Gutkowski"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Erica Schiller"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gilbert Rath"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kate Watsica"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Brian Wilkinson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Nellie Koepp"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Betsy Jaskolski"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lorena Krajcik"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Casey Hamill"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Peggy Marvin"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Corey Effertz"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kristin Prosacco"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Anna Pagac"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Jesse Rippin"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Rudy Cole"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Ginger Schinner"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Maggie Harber"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rogelio Boyer"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intelligent Frozen Keyboard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantastic Granite Chips"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tasty Rubber Fish"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tasty Granite Shirt"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rustic Cotton Mouse"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Unbranded Plastic Mouse"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sleek Plastic Shoes"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Refined Frozen Cheese"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Incredible Frozen Towels"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fantastic Wooden Towels"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Awesome Metal Hat"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Handmade Concrete Mouse"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sleek Plastic Towels"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Refined Soft Pants"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Unbranded Wooden Chicken"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Incredible Fresh Table"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sleek Cotton Bike"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Handcrafted Plastic Mouse"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Rustic Granite Car"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ergonomic Wooden Shoes"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
